don't use buffer constructor
zapier/zapier-platform-core pull request #60
Opened 2017-12-21 21:31 UTC by xavdid

Cousin PR of [this one](https://github.com/zapier/zapier-platform-cli/pull/213).

There's also a change to use `Buffer.isBuffer` instead of `_.isBuffer`, which uses the former under the hood. Consistency seems like a good thing.

2017-12-25 06:29 UTC, eliangcs requested changes
Instead of `new Buffer.from()`, I think you meant to write `Buffer.from()`. But strangely enough, `new Buffer.from()` actually works like `Buffer.from()`:

```
> new Buffer.from('aa')
<Buffer 61 61>
> Buffer.from('aa')
<Buffer 61 61>
```

2017-12-25 06:29 UTC, eliangcs commented on integration-test/integration-test.js
> +      const logs = new Buffer.from(data.LogResult, 'base64').toString();
`new` should be removed here.

2017-12-25 06:29 UTC, eliangcs commented on test/create-request-client.js
> +      body: new Buffer.from('hello world this is a cat (=^..^=)')
`new` should be removed.

2017-12-25 06:29 UTC, eliangcs commented on test/tools/file-stasher.js
> +    const file = new Buffer.from('hello world this is a buffer of text');
Same here.

2017-12-26 19:33 UTC, xavdid commented
ah, you're super right! i had a little bit of tunnel vision with regards to changing the constructor to `.from`, haha. I've updated!

2017-12-27 02:34 UTC, eliangcs approved these changes

2017-12-27 04:17 UTC, merged